services:
  - id: service1
    port: 7777
    hosts:
      - ip: "service-discovery-svc1-1"
        status: ""
      - ip: "service-discovery-svc1-2"
        status: ""
      - ip: "service-discovery-svc1-3"
        status: ""
  - id: service2
    port: 9999
    hosts:
      - ip: "service-discovery-svc2-1"
        status: ""
      - ip: "service-discovery-svc2-2"
        status: ""
      - ip: "service-discovery-svc2-3"
        status: ""